pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage('Deploy') {
            steps {
                sh '''
                    oc project lsm-deploy-strategies 
                    oc start-build greeting-service --follow --wait
                ''' }
                }
    }
}
